# Generated by Django 2.1.2 on 2019-01-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
    ]
