# Generated by Django 2.1.2 on 2019-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0002_remove_lesson_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_info',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LessonInfo',
        ),
    ]
