# Generated by Django 2.1.2 on 2019-01-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0006_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='data',
            new_name='date',
        ),
    ]
