# Generated by Django 2.1.2 on 2019-01-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0007_auto_20190123_1314'),
        ('calendar_', '0007_auto_20190123_0648'),
    ]

    operations = [
    ]
