# Generated by Django 2.1.2 on 2019-01-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0008_merge_20190123_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='group',
            name='number_of_clients',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(to='calendar_.Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Нет заголовка', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='client',
            name='group',
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ManyToManyField(to='calendar_.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_.Course'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_.Client'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_.Group'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_.Client'),
        ),
    ]
