# Generated by Django 2.1.2 on 2019-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0009_auto_20190123_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.ManyToManyField(blank=True, to='calendar_.Group'),
        ),
    ]
