# Generated by Django 2.1.2 on 2019-01-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0012_auto_20190123_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
