# Generated by Django 2.1.2 on 2019-01-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0013_auto_20190123_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birth_date',
        ),
    ]
